source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'EmptyProject' do
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 4.0.0'
pod 'MobAPI-For-iOS'
pod 'MOBFoundation'
end
